In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mp

#### inicializando el dataset

In [9]:
datos = pd.read_csv("./games.csv", index_col="Id")
datos.head()

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
Id,,,,,,,,,,,,,
0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

#### Dimension del dataset

In [10]:
print (f"cantidad de filas y columnas del dataset: {datos.shape}")

cantidad de filas y columnas del dataset: (1512, 13)

#### mostrando informacion del dataset

In [11]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1512 entries, 0 to 1511
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              1512 non-null   object
 1   Release Date       1512 non-null   object
 2   Team               1511 non-null   object
 3   Rating             1499 non-null   float64
 4   Times Listed       1512 non-null   object
 5   Number of Reviews  1512 non-null   object
 6   Genres             1512 non-null   object
 7   Summary            1511 non-null   object
 8   Reviews            1512 non-null   object
 9   Plays              1512 non-null   object
 10  Playing            1512 non-null   object
 11  Backlogs           1512 non-null   object
 12  Wishlist           1512 non-null   object
dtypes: float64(1), object(12)
memory usage: 165.4+ KB

#### mostrando las filas de datos nulos

In [12]:
datos.isnull()

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
Id,,,,,,,,,,,,,
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,False,False,False,False,False,False,False,False,False,False,False,False,False
1508,False,False,False,False,False,False,False,False,False,False,False,False,False
1509,False,False,False,False,False,False,False,False,False,False,False,False,False
1510,False,False,False,False,False,False,False,False,False,False,False,False,False
1511,False,False,False,False,False,False,False,False,False,False,False,False,False

#### identificando las columnas con datos nulos

In [13]:
datos.isnull().any()

Title                False
Release Date         False
Team                  True
Rating                True
Times Listed         False
Number of Reviews    False
Genres               False
Summary               True
Reviews              False
Plays                False
Playing              False
Backlogs             False
Wishlist             False
dtype: bool

#### identificando las filas en especificas con datos nulos

In [20]:

filas_nulas = datos[datos.isnull().any(axis=1)]
print(filas_nulas)

                                                  Title     Release Date  \
Id
587                                   Final Fantasy XVI     Jun 22, 2023
649                                   Death Stranding 2  releases on TBD
713                           Final Fantasy VII Rebirth     Dec 31, 2023
719                                           Lies of P     Aug 01, 2023
726                                               Judas     Mar 31, 2025
746   Like a Dragon Gaiden: The Man Who Erased His Name     Dec 31, 2023
972           The Legend of Zelda: Tears of the Kingdom     May 12, 2023
1130                           Star Wars Jedi: Survivor     Apr 28, 2023
1160            We Love Katamari Reroll + Royal Reverie     Jun 02, 2023
1202                                         Earthblade     Dec 31, 2024
1245                               NEET Girl Date Night     Oct 21, 2022
1305                                          Diablo IV     Jun 06, 2023
1341                                   Pac-Man in a Tin     Mar 22, 2023
1349                                       Pokémon Añil     Mar 23, 2023

                                                   Team  Rating Times Listed  \
Id
587   ['Square Enix', 'Square Enix Creative Business...     NaN          422
649                              ['Kojima Productions']     NaN          105
713                                     ['Square Enix']     NaN          192
719                         ['NEOWIZ', 'Round8 Studio']     NaN          175
726                               ['Ghost Story Games']     NaN           90
746                   ['Ryū Ga Gotoku Studios', 'Sega']     NaN          118
972   ['Nintendo', 'Nintendo EPD Production Group No...     NaN          581
1130       ['Respawn Entertainment', 'Electronic Arts']     NaN          250
1160  ['Bandai Namco Entertainment', 'MONKEYCRAFT Co...     NaN           51
1202                             ['Extremely OK Games']     NaN           83
1245                                                NaN     2.7           21
1305                         ['Blizzard Entertainment']     NaN          148
1341                                 ['Fizz Creations']     NaN            0
1349                                      ['Eric Lost']     NaN            2

     Number of Reviews                           Genres  \
Id
587                422                          ['RPG']
649                105         ['Adventure', 'Shooter']
713                192                               []
719                175                          ['RPG']
726                 90         ['Adventure', 'Shooter']
746                118  ['Adventure', 'Brawler', 'RPG']
972                581             ['Adventure', 'RPG']
1130               250                    ['Adventure']
1160                51          ['Adventure', 'Puzzle']
1202                83    ['Adventure', 'Indie', 'RPG']
1245                21                 ['Visual Novel']
1305               148               ['Brawler', 'RPG']
1341                 0                       ['Arcade']
1349                 2                          ['RPG']

                                                Summary  \
Id
587   Final Fantasy XVI is an upcoming action role-p...
649                                                 NaN
713   This next standalone chapter in the FINAL FANT...
719   Inspired by the familiar story of Pinocchio, L...
726   A disintegrating starship. A desperate escape ...
746   This game covers Kiryu's story between Yakuza ...
972   The Legend of Zelda: Tears of the Kingdom is t...
1130  The story of Cal Kestis continues in Star Wars...
1160  We Love Katamari Reroll + Royal Reverie is a r...
1202  You are Névoa, an enigmatic child of Fate retu...
1245  Your friend sets you up on a date with his NEE...
1305  Endless demons to slaughter. Deep customizatio...
1341  Pac-Man in a Tin is a pocket-sized tin contain...
1349  Pokémon Añil is the fourth video game created ...

                                                Reviews Plays Playing  \
Id
587                                                  []    37      10
649                                                  []     3       0
713                                                  []    20       3
719                                                  []     5       0
726                                                  []     1       0
746                                                  []     2       1
972                                                  []    72       6
1130                                                 []    13       2
1160                                                 []     3       0
1202                                                 []     0       1
1245  ['this sucked. "Omg she is literally me" is no...   106       1
1305                                                 []    19      10
1341                                                 []     1       0
1349  ['pokemon HWHAT', 'Finally, after all these ye...     1       0

     Backlogs Wishlist
Id
587       732     2.4K
649       209      644
713       354     1.1K
719       260      939
726        92      437
746       145      588
972      1.6K     5.4K
1130      367     1.4K
1160       74      291
1202      103      529
1245       44       42
1305      179      677
1341        1        2
1349        1        7

#### eliminando los datos nulos del dataset

In [21]:
data_sin_nulos = datos.dropna()
data_sin_nulos

,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
Id,,,,,,,,,,,,,
0,Elden Ring,"Feb 25, 2022","['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,Hades,"Dec 10, 2019",['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,The Legend of Zelda: Breath of the Wild,"Mar 03, 2017","['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,Undertale,"Sep 15, 2015","['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,Hollow Knight,"Feb 24, 2017",['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507,Back to the Future: The Game,"Dec 22, 2010",['Telltale Games'],3.2,94,94,"['Adventure', 'Point-and-Click']",Back to the Future: The Game is one of Telltal...,['Very enjoyable game. The story adds onto the...,763,5,223,67
1508,Team Sonic Racing,"May 21, 2019","['Sumo Digital', 'Sega']",2.9,264,264,"['Arcade', 'Racing']",Team Sonic Racing combines the best elements o...,"['jogo morto mas bom', 'not my cup of tea', ""C...",1.5K,49,413,107
1509,Dragon's Dogma,"May 22, 2012",['Capcom'],3.7,210,210,"['Brawler', 'RPG']","Set in a huge open world, Dragon’s Dogma: Dark...","['Underrated.', 'A grandes rasgos, es como un ...",1.1K,45,487,206
1510,Baldur's Gate 3,"Oct 06, 2020",['Larian Studios'],4.1,165,165,"['Adventure', 'RPG', 'Strategy', 'Tactical', '...","An ancient evil has returned to Baldur's Gate,...",['Bu türe bu oyunla girmeye çalışmak hataydı s...,269,79,388,602
1511,The LEGO Movie Videogame,"Feb 04, 2014","['WB Games', 'TT Fusion']",2.8,184,184,"['Adventure', 'Puzzle']",Join Emmet and an unlikely group of resistance...,"['Legal', 'Pretty Average Lego Game But It Was...",1.7K,11,239,73

#### funcion para verificar si el genero rpg esta presente en la lista

In [30]:
def filtro_rpg(genres):
    return "RPG" in genres
#APLICA EL FILTRO UTILIZANDO APPLY
datosRPG = datos[datos["Genres"].apply(filtro_rpg)]
#MUESTRA EL DATASET SOLAMENTE INCLUYENDO LA COLUMNAS TITULO Y RANKING
nombresRPG = datosRPG[["Title","Rating"]]
nombresRPG.head(20)
#no ocupar este dataset porque "datos" esta con nulos

                                      Title  Rating
Id
0                                Elden Ring     4.5
1                                     Hades     4.3
2   The Legend of Zelda: Breath of the Wild     4.4
3                                 Undertale     4.2
6                                     Omori     4.2
9                            NieR: Automata     4.3
10                          Persona 5 Royal     4.4
12                               God of War     4.2
14                               Bloodborne     4.5
16                                 Yakuza 0     4.4
17                    Red Dead Redemption 2     4.4
20                  Pokémon Legends: Arceus     3.7
24                           Cyberpunk 2077     3.3
26                   Xenoblade Chronicles 3     4.4
28             Disco Elysium: The Final Cut     4.6
30                           Dark Souls III     4.2
31      NieR Replicant ver.1.22474487139...     4.2
36                        Final Fantasy VII     4.2
37                         Persona 4 Golden     4.2
38                           Genshin Impact     2.6

#### informacion del dataset ya filtrado

In [31]:
nombresRPG.info()
#sigue con error porque esta con nulos

<class 'pandas.core.frame.DataFrame'>
Index: 523 entries, 0 to 1510
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   523 non-null    object
 1   Rating  516 non-null    float64
dtypes: float64(1), object(1)
memory usage: 12.3+ KB

#### Hacer nuevamente el dataframe sin nulos

#### mostrando los primeros 10 videojuegos rpg y su rating de popularidad

In [35]:
datasetRPG = nombresRPG.head(10)

datasetRPG.drop(["title"], axis=1)["rating"].plot(kind="bar")

KeyError: "['title'] not found in axis"